---
deployment:
  tasks:
    - /bin/rsync -av --delete --exclude='.git' --exclude='.github' --exclude='.vscode' --exclude='.DS_Store' --exclude='README.txt' --exclude='MakeSenseData.code-workspace' --exclude='Archive' /home1/wsbiadmy/repositories/makesensedata/ /home1/wsbiadmy/public_html/website_b8322a24/