---
deployment:
 tasks:
 - export DEPLOYPATH=/home1/wsbiadmy/public_html/website_b8322a24/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH
 - /bin/cp -R assets $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH
 - /bin/cp -R gender-pay-analytics $DEPLOYPATH